# Generated by Django 4.2 on 2024-02-16 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRefNumberGen',
            fields=[
                ('MentorRefNumberRan', models.CharField(max_length=33, primary_key='MentorRefNumberRan', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRepProfile',
            fields=[
                ('StudentNumber', models.CharField(max_length=15, primary_key='StudentNumber', serialize=False)),
                ('AreaOfStudy', models.CharField(max_length=20, null=True)),
                ('DOB', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('StudentNumber', models.CharField(max_length=15, primary_key='StudentNumber', serialize=False)),
                ('AreaOfStudy', models.CharField(max_length=20, null=True)),
                ('DOB', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaOfStudy', models.CharField(max_length=20, null=True)),
                ('DOB', models.DateField(null=True)),
                ('MentorRefNumber', models.OneToOneField(max_length=33, on_delete=django.db.models.deletion.DO_NOTHING, to='users.mentorrefnumbergen')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
