# Generated by Django 4.2 on 2024-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='Image',
            field=models.ImageField(default='defaultprofileimage.png', upload_to='mentor_pics'),
        ),
    ]
