# Generated by Django 4.2 on 2024-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='Image',
            field=models.ImageField(default='defaultpi.png', upload_to='mentor_pics'),
        ),
    ]
