# Generated by Django 4.2 on 2024-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentrepprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrepprofile',
            name='Image',
            field=models.ImageField(default='defaultpi.png', upload_to='rep_pics'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='Description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentrepprofile',
            name='Description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
