# Generated by Django 4.2.3 on 2024-04-28 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofpost', models.CharField(choices=[('Problem', 'Problem'), ('Discussion', 'Discussion')], max_length=50)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('timesubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
