# Generated by Django 4.2.3 on 2024-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
