# Generated by Django 4.2.3 on 2024-04-25 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_message_conversation_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageA',
        ),
    ]
