# Generated by Django 4.2.3 on 2024-04-25 23:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_rename_message_messagea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageA',
            new_name='Text',
        ),
    ]
